-- ============================================
-- TikTok KOL Platform Database Schema
-- Phase 1: Creator Identity & Contact Management
-- ============================================
-- Generated by Prisma Migration: 20260212082108_init_kol_platform
-- Database: PostgreSQL
-- ============================================

-- Create Enum for User Roles
CREATE TYPE "user_role" AS ENUM ('ADMIN', 'BRAND', 'AGENCY', 'CREATOR');

-- ============================================
-- Table: users
-- Purpose: User authentication and access control
-- ============================================
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "role" "user_role" NOT NULL DEFAULT 'BRAND',
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- ============================================
-- Table: agencies
-- Purpose: Talent agencies managing creators
-- ============================================
CREATE TABLE "agencies" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "contact_email" VARCHAR(255),
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "agencies_pkey" PRIMARY KEY ("id")
);

-- ============================================
-- Table: creators
-- Purpose: TikTok creators/KOL profiles
-- ============================================
CREATE TABLE "creators" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "tiktok_username" VARCHAR(255) NOT NULL,
    "tiktok_profile_url" VARCHAR(500) NOT NULL,
    "content_language" VARCHAR(100),
    "city" VARCHAR(100),
    "country" VARCHAR(100),
    "agency_id" UUID,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "creators_pkey" PRIMARY KEY ("id")
);

-- ============================================
-- Table: creator_contacts
-- Purpose: Encrypted contact information for creators
-- ============================================
CREATE TABLE "creator_contacts" (
    "id" UUID NOT NULL,
    "creator_id" UUID NOT NULL,
    "email_encrypted" TEXT,
    "whatsapp_encrypted" TEXT,
    "is_verified" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "creator_contacts_pkey" PRIMARY KEY ("id")
);

-- ============================================
-- Table: contact_unlocks
-- Purpose: Audit log for contact information unlocks
-- ============================================
CREATE TABLE "contact_unlocks" (
    "id" UUID NOT NULL,
    "creator_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "unlocked_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "contact_unlocks_pkey" PRIMARY KEY ("id")
);

-- ============================================
-- Indexes
-- ============================================

-- Users table indexes
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE INDEX "users_email_idx" ON "users"("email");

-- Creators table indexes
CREATE UNIQUE INDEX "creators_tiktok_username_key" ON "creators"("tiktok_username");
CREATE INDEX "creators_tiktok_username_idx" ON "creators"("tiktok_username");
CREATE INDEX "creators_agency_id_idx" ON "creators"("agency_id");

-- Creator contacts table indexes
CREATE UNIQUE INDEX "creator_contacts_creator_id_key" ON "creator_contacts"("creator_id");

-- Contact unlocks table indexes
CREATE INDEX "contact_unlocks_creator_id_idx" ON "contact_unlocks"("creator_id");
CREATE INDEX "contact_unlocks_user_id_idx" ON "contact_unlocks"("user_id");

-- ============================================
-- Foreign Key Constraints
-- ============================================

-- Creators -> Agencies (SET NULL on delete)
ALTER TABLE "creators" 
    ADD CONSTRAINT "creators_agency_id_fkey" 
    FOREIGN KEY ("agency_id") 
    REFERENCES "agencies"("id") 
    ON DELETE SET NULL 
    ON UPDATE CASCADE;

-- Creator Contacts -> Creators (CASCADE on delete)
ALTER TABLE "creator_contacts" 
    ADD CONSTRAINT "creator_contacts_creator_id_fkey" 
    FOREIGN KEY ("creator_id") 
    REFERENCES "creators"("id") 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;

-- Contact Unlocks -> Creators (RESTRICT on delete - preserve audit)
ALTER TABLE "contact_unlocks" 
    ADD CONSTRAINT "contact_unlocks_creator_id_fkey" 
    FOREIGN KEY ("creator_id") 
    REFERENCES "creators"("id") 
    ON DELETE RESTRICT 
    ON UPDATE CASCADE;

-- Contact Unlocks -> Users (RESTRICT on delete - preserve audit)
ALTER TABLE "contact_unlocks" 
    ADD CONSTRAINT "contact_unlocks_user_id_fkey" 
    FOREIGN KEY ("user_id") 
    REFERENCES "users"("id") 
    ON DELETE RESTRICT 
    ON UPDATE CASCADE;

-- ============================================
-- End of Schema
-- ============================================
